// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: internal/proto/octo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	Data_UnknownData DataType = 0
	Data_LogPassData DataType = 1
	Data_TextData    DataType = 2
	Data_BinaryData  DataType = 3
	Data_CardData    DataType = 4
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "UnknownData",
		1: "LogPassData",
		2: "TextData",
		3: "BinaryData",
		4: "CardData",
	}
	DataType_value = map[string]int32{
		"UnknownData": 0,
		"LogPassData": 1,
		"TextData":    2,
		"BinaryData":  3,
		"CardData":    4,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_octo_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_internal_proto_octo_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{0, 0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rtype DataType `protobuf:"varint,3,opt,name=rtype,proto3,enum=myproto.DataType" json:"rtype,omitempty"`
	Meta  []byte   `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Data  []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data) GetRtype() DataType {
	if x != nil {
		return x.Rtype
	}
	return Data_UnknownData
}

func (x *Data) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendArrayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arr []*Data `protobuf:"bytes,1,rep,name=arr,proto3" json:"arr,omitempty"`
}

func (x *SendArrayRequest) Reset() {
	*x = SendArrayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendArrayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendArrayRequest) ProtoMessage() {}

func (x *SendArrayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendArrayRequest.ProtoReflect.Descriptor instead.
func (*SendArrayRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{1}
}

func (x *SendArrayRequest) GetArr() []*Data {
	if x != nil {
		return x.Arr
	}
	return nil
}

type SendArrayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendArrayResponse) Reset() {
	*x = SendArrayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendArrayResponse) ProtoMessage() {}

func (x *SendArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendArrayResponse.ProtoReflect.Descriptor instead.
func (*SendArrayResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{2}
}

func (x *SendArrayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetArrayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *GetArrayRequest) Reset() {
	*x = GetArrayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArrayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArrayRequest) ProtoMessage() {}

func (x *GetArrayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArrayRequest.ProtoReflect.Descriptor instead.
func (*GetArrayRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{3}
}

func (x *GetArrayRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetArrayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arr   []*Data `protobuf:"bytes,1,rep,name=arr,proto3" json:"arr,omitempty"`
	Error string  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetArrayResponse) Reset() {
	*x = GetArrayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArrayResponse) ProtoMessage() {}

func (x *GetArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArrayResponse.ProtoReflect.Descriptor instead.
func (*GetArrayResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{4}
}

func (x *GetArrayResponse) GetArr() []*Data {
	if x != nil {
		return x.Arr
	}
	return nil
}

func (x *GetArrayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Стрим файла с агента [запрос].
type FileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{5}
}

func (x *FileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Стрим файла с агента [ответ].
type FileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{6}
}

func (x *FileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Стрим файла с сервера [запрос].
type FileStreamServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFile string `protobuf:"bytes,1,opt,name=idFile,proto3" json:"idFile,omitempty"`
}

func (x *FileStreamServerRequest) Reset() {
	*x = FileStreamServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStreamServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStreamServerRequest) ProtoMessage() {}

func (x *FileStreamServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStreamServerRequest.ProtoReflect.Descriptor instead.
func (*FileStreamServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{7}
}

func (x *FileStreamServerRequest) GetIdFile() string {
	if x != nil {
		return x.IdFile
	}
	return ""
}

// Стрим файла с сервера [ответ].
type FileStreamServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileStreamServerResponse) Reset() {
	*x = FileStreamServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStreamServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStreamServerResponse) ProtoMessage() {}

func (x *FileStreamServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStreamServerResponse.ProtoReflect.Descriptor instead.
func (*FileStreamServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{8}
}

func (x *FileStreamServerResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *LoginResponce) Reset() {
	*x = LoginResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponce) ProtoMessage() {}

func (x *LoginResponce) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponce.ProtoReflect.Descriptor instead.
func (*LoginResponce) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{10}
}

func (x *LoginResponce) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *RegRequest) Reset() {
	*x = RegRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegRequest) ProtoMessage() {}

func (x *RegRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegRequest.ProtoReflect.Descriptor instead.
func (*RegRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{11}
}

func (x *RegRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RegResponce) Reset() {
	*x = RegResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_octo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegResponce) ProtoMessage() {}

func (x *RegResponce) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_octo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegResponce.ProtoReflect.Descriptor instead.
func (*RegResponce) Descriptor() ([]byte, []int) {
	return file_internal_proto_octo_proto_rawDescGZIP(), []int{12}
}

func (x *RegResponce) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_internal_proto_octo_proto protoreflect.FileDescriptor

var file_internal_proto_octo_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6f, 0x63, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x79, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x05, 0x72, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x4c, 0x6f, 0x67, 0x50, 0x61, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x10, 0x04, 0x22, 0x33, 0x0a, 0x10, 0x53, 0x65, 0x6e,
	0x64, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x03, 0x61, 0x72, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x79, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x61, 0x72, 0x72, 0x22, 0x29,
	0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x29, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x61, 0x72, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x61, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x21, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x24, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x17, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x2e, 0x0a, 0x18, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0c, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x3c, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x23, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xa7, 0x02, 0x0a, 0x04, 0x4f, 0x63, 0x74, 0x6f, 0x12, 0x42,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x19, 0x2e, 0x6d, 0x79,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x18,
	0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x14, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x12, 0x5b, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x32,
	0x79, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x36, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x15, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x13, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_octo_proto_rawDescOnce sync.Once
	file_internal_proto_octo_proto_rawDescData = file_internal_proto_octo_proto_rawDesc
)

func file_internal_proto_octo_proto_rawDescGZIP() []byte {
	file_internal_proto_octo_proto_rawDescOnce.Do(func() {
		file_internal_proto_octo_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_octo_proto_rawDescData)
	})
	return file_internal_proto_octo_proto_rawDescData
}

var file_internal_proto_octo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_octo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_octo_proto_goTypes = []any{
	(DataType)(0),                    // 0: myproto.Data.type
	(*Data)(nil),                     // 1: myproto.Data
	(*SendArrayRequest)(nil),         // 2: myproto.SendArrayRequest
	(*SendArrayResponse)(nil),        // 3: myproto.SendArrayResponse
	(*GetArrayRequest)(nil),          // 4: myproto.GetArrayRequest
	(*GetArrayResponse)(nil),         // 5: myproto.GetArrayResponse
	(*FileRequest)(nil),              // 6: myproto.FileRequest
	(*FileResponse)(nil),             // 7: myproto.FileResponse
	(*FileStreamServerRequest)(nil),  // 8: myproto.FileStreamServerRequest
	(*FileStreamServerResponse)(nil), // 9: myproto.FileStreamServerResponse
	(*LoginRequest)(nil),             // 10: myproto.LoginRequest
	(*LoginResponce)(nil),            // 11: myproto.LoginResponce
	(*RegRequest)(nil),               // 12: myproto.RegRequest
	(*RegResponce)(nil),              // 13: myproto.RegResponce
}
var file_internal_proto_octo_proto_depIdxs = []int32{
	0,  // 0: myproto.Data.rtype:type_name -> myproto.Data.type
	1,  // 1: myproto.SendArrayRequest.arr:type_name -> myproto.Data
	1,  // 2: myproto.GetArrayResponse.arr:type_name -> myproto.Data
	2,  // 3: myproto.Octo.SendArray:input_type -> myproto.SendArrayRequest
	4,  // 4: myproto.Octo.GetArray:input_type -> myproto.GetArrayRequest
	6,  // 5: myproto.Octo.StreamFile:input_type -> myproto.FileRequest
	8,  // 6: myproto.Octo.ServerStreamFile:input_type -> myproto.FileStreamServerRequest
	10, // 7: myproto.Auth.Login:input_type -> myproto.LoginRequest
	12, // 8: myproto.Auth.Registration:input_type -> myproto.RegRequest
	3,  // 9: myproto.Octo.SendArray:output_type -> myproto.SendArrayResponse
	5,  // 10: myproto.Octo.GetArray:output_type -> myproto.GetArrayResponse
	7,  // 11: myproto.Octo.StreamFile:output_type -> myproto.FileResponse
	9,  // 12: myproto.Octo.ServerStreamFile:output_type -> myproto.FileStreamServerResponse
	11, // 13: myproto.Auth.Login:output_type -> myproto.LoginResponce
	13, // 14: myproto.Auth.Registration:output_type -> myproto.RegResponce
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_octo_proto_init() }
func file_internal_proto_octo_proto_init() {
	if File_internal_proto_octo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_octo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SendArrayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SendArrayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetArrayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetArrayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FileStreamServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FileStreamServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*LoginResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RegRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_octo_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RegResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_octo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_octo_proto_goTypes,
		DependencyIndexes: file_internal_proto_octo_proto_depIdxs,
		EnumInfos:         file_internal_proto_octo_proto_enumTypes,
		MessageInfos:      file_internal_proto_octo_proto_msgTypes,
	}.Build()
	File_internal_proto_octo_proto = out.File
	file_internal_proto_octo_proto_rawDesc = nil
	file_internal_proto_octo_proto_goTypes = nil
	file_internal_proto_octo_proto_depIdxs = nil
}
